### PR TITLE
[WIP] Refactor

### LINKED ISSUE #34: Split script into logically seperated multiple files
Would you consider accepting a PR that refactors out things like UI and settings into different scripts? Folds are ok but it is still unruly trying to jump between different parts of the script or find something you need to check or change, which leads to bugs and forgotten implementations.

Having multiple files `#include`d makes things much clearer to read the project.

For an idea of how this might work, see my fork.

### PR DESCRIPTION
**Pull request by BlueDrink9**
# TODO

- [x] Split script into separate files (Fixes #34)
- [ ] Convert labels to functions
- [ ] Refactor variable names
- [ ] Move any vim* functions and variables into a vim class. (If possible, add a file containing backwards-compatible stubs).
- [ ] Refactor GUI code to add all gui elements using functions.
- [ ] (If possible) refactor pages of hotkeys to use macros.
- [ ] General refactor of functions, variables, code position.

### CODE REVIEW

**Comment by BlueDrink9** [comment]
(This fixes #34)

@rcmdnk can you tell me some of the functions/variables you call from other scripts? What you might consider most similar to a public API? I'll create wrappers so that they don't lose backwards-compatibility.

**Comment by rcmdnk** [comment]
Values of `Options` in README should be changeable from the parent script.
But if we want to classes for this script, CUI setting should be changed, too.

Anyway, I think we should start to make classes before splitting files.
Otherwise, we can not decide the policy of splitting.

**Comment by BlueDrink9** [comment]
The reverse also applies: to know the classes, we have to spit the script anyway

**Comment by BlueDrink9** [comment]
But sure, any settings will have an api left for them, same as current.

**Comment by rcmdnk** [comment]
I'm starting to implement classes 
and replace labels to functions to reduce global variables.

https://github.com/rcmdnk/vim_ahk/blob/class/vim.ahk

I think this kind of work makes the way to split files clearly, too,
although the above branch is still under development and not so beautiful.

**Comment by BlueDrink9** [comment]
Ok, if I discard my changes and pull yours, then make edits, are you happy to cherry-pick my changes too? Or do you want to make a separate PR?

I haven't done a collaborative PR before so I don't know how easy git makes it to add commits from two authors. Can you push directly to this PR branch??

**Comment by rcmdnk** [comment]
If you agree with [class](https://github.com/rcmdnk/vim_ahk/tree/class) branch structure, then it is easier to start from the branch.

**Comment by BlueDrink9** [comment]
Sure. I'll reset this PR to your branch, and push changes. What is your timezone and working hours? I'm GMT+12, working 0900-2000. So long as we push frequently, I'll pull each morning and we shouldn't end up with conflicts.

**Comment by BlueDrink9** [comment]
It would make the process much easier if you check out and add this pull request as a remote. That way we can both collaborate on it. You have push access to it.

Also, I still think we should remove 'vim' at the start of everything. It's implied. It should only be used for the api. Instead of each new file being `vim_something`, they should have normal names but be called from a single `vim` class.

If you look at https://github.com/rcmdnk/vim_ahk/pull/40/commits/5b3426409baa8b9df14c8490f503fdc30c4d6cd5, you'll see I actually moved all the code into a new folder (I called it src where you used lib) and left vim.ahk as a stub. This stub can also have an api like:

```
VimReadIni(){
    vim.settings.readIni()
}
```

Does that make sense?

**Comment by BlueDrink9** [comment]
To avoid having to name things the redundant `vim[name]`, the includes could be wrapped in a class in the main script, like:

```autohotkey
class Vim{
    #Include %A_LineFile%\..\lib\vim_about.ahk
    #Include %A_LineFile%\..\lib\vim_conf.ahk
    #Include %A_LineFile%\..\lib\vim_debug.ahk
    #Include %A_LineFile%\..\lib\vim_icon_mng.ahk
    #Include %A_LineFile%\..\lib\vim_ini.ahk
    #Include %A_LineFile%\..\lib\vim_menu.ahk
    #Include %A_LineFile%\..\lib\vim_state.ahk
}
```

That way, instead of being accessed as `VimConf.Verbose` they can be accessed like `Vim.Conf.Verbose`, which I think is clearer and tidier. It keeps things nicely separated.

Also, for backwards compatibility, the main script can include an (optional?) api, like

```autohotkey
VimReadIni(){
    Vim.Ini.ReadIni()
}
```

For variables it gets a bit trickier, but I think you could do something like:

```
VimVerbose = &Vim.Conf.Verbose
```

Dereferencing may be an issue though, I'll check it.

**Comment by rcmdnk** [comment]
I'm at GMT+9, but I almost can't touch the script during the working hour.
It could be only in the night or holidays, or sometime when I can get a time...

**Comment by rcmdnk** [comment]
There are some limitations I have already found.
To minimize the things, I use class variables as global variables, which is not so cool.

Another thing that I could not implement is to implement the class method for SetTimer.
For now, I just make global functions and use them.

Control variables used for the settings also must be global or static, and I just let them global, but there is no good way to specify in VimSetting.Menu function.

**Comment by BlueDrink9** [comment]
Ok. If you push to this pull request branch, I will help work on it tomorrow. Otherwise I can only let you work on it yourself.

Can you please explain: what do you mean by "use class variables as global variables"?

> Control variables used for the settings also must be global or static, and I just let them global, but there is no good way to specify in VimSetting.Menu function.

No good way to specify what? To set variables from outside the script, do you mean?

**Comment by BlueDrink9** [comment]
Anyway, the changes made so far are a big improvement

**Comment by BlueDrink9** [comment]
> Another thing that I could not implement is to implement the class method for SetTimer.

Are the timers only used to detect when the window changes? I have a function that registers for the Windows system event to notify it when the active window changes, so it's actually more efficient (and instant). Would it be helpful to replace the timers with that?

**Comment by rcmdnk** [comment]
> Can you please explain: what do you mean by "use class variables as global variables"?

For example, `VimRestoreIME` must be global to use as v-label in settings.
But it is not possible to do something like:

    for k, v in VimConf.Conf{
      global %k%
    }

then, it must be declared explicitly.
There are too many and will be changed, therefore I just use `global` and add `local` to each local variable in the function.

**Comment by rcmdnk** [comment]
> Do these dummies still work now that they are functions, not labels?
Functions work as same as labels in the recent AHK.
You can see a popup on the text in the setting window (such as `Verbose level`)

**Comment by rcmdnk** [comment]
> Are the timers only used to detect when the window changes?

It is for tooltips, to delay and remove after some time.

https://github.com/rcmdnk/vim_ahk/blob/58a36962b38f72a94adb2893548f2161d86e92b8/lib/vim_setting.ahk#L64

In `MouseMove`, I tried to use `VimDisplayToolTip` in the class (which is currently commented out), but it does not work well.
It partly works, but it seems every `f := ObjBindMethod(VimSetting, "VimDisplayToolTip")` set different object, i.e. `VimDisplayToolTip` works and make a popup, but it continues to make popup every 1000ms because `f := ObjBindMethod(VimSetting, "VimDisplayToolTip")` gets different object in `VimDisplayToolTip` and set off for the different object. (maybe)

**Comment by BlueDrink9** [comment]
I see. That would make wrapping the includes in a `class` difficult.

**Comment by BlueDrink9** [comment]
Ok. I decided to wrap the callback function I was talking about and release it anyway. https://github.com/BlueDrink9/ahk-detect_window_change

**Pull request closed without merging**
