### PR TITLE
Update vim.ahk: #Requires AutoHotkey v1.1

### PR DESCRIPTION
**Pull request by mangost**

### CODE REVIEW

**Comment by rcmdnk** [comment]
Thank you for your pull request!

Could you please change the version number from 1.0 to 1.1?

The Requires directive was introduced in version 1.1.33.00 (released in Jun/2020) of AutoHotkey in June 2020.
Therefore, the minimum version requirement should be specified as follows:

```
#Requires AutoHotkey v1.1                                                       
```

However, a more precise specification might be beneficial:

```
#Requires AutoHotkey >=1.1.33.00 <2.0
```

But do note that this specification requires at least version 1.1.36 (released in Dec/2022).

Until version 1.2 is released, specifying v1.1 allows for broader compatibility. While this approach does drop support for older versions (earlier than v1.1.33.00), it offers significant benefits when used with version 2.



[Changes & New Features | AutoHotkey v1](https://www.autohotkey.com/docs/v1/AHKL_ChangeLog.htm)
[#Requires - Syntax & Usage | AutoHotkey v1](https://www.autohotkey.com/docs/v1/lib/_Requires.htm)

**Comment by rcmdnk** [comment]
Also, I would like to migrate to V2, though there has been no progress yet...
#95

**Comment by mangost** [comment]
It's now 

```
#Requires AutoHotkey v1.1
```

Thanks for the summary on version compatibility of autohotkey. I have never read through the document, and it's the first time I learned about it.

**Comment by rcmdnk** [comment]
I wasn't aware of the 'Requires' feature either.

Anyway, thank you for your update. I'll proceed with the merge.

**Pull request merged**
