### PR TITLE
Add support for win10, onenote and vs code; Restore IME status

### PR DESCRIPTION
**Pull request by luciferz2012**
See all 5 commit messages for detail.

Thank you for your work, it is super efficient!

### CODE REVIEW

**Comment by rcmdnk** [comment]
Thank you for your pull request.

I have some comments on them:

- Tool tips seem good and works in Win7, too. so I would implement it.
I prefer the position of `W*3/4`, `H*3/4`, and SetTimer 1000 instead of 16000.

In addition, could you please show

        Status(VimMode "`r`ng=" Vim_g "`r`nn=" Vim_n)

for verbose level 2 instead of simple VimMode.

- About LastIME:
    - LastIME -> VimLastIME
    - Add `VimRestoreIME=1` after the line of `vim_verbose=0`, and change:

            - If(Mode=="Insert"){
            + If(Mode=="Insert") and (VimRestoreIME==1){

        so that IME restoring can be disabled easily. But I think this can be default (then 1 is set).

- New VimGroups are welcome.
- About DoubleHome, what happens when HOME is pushed once? (I don't use Visual Studio then I don't know what happens at all...)
- About OneNote, what happens when {UP} or {DOWN} is used? If it makes not normal cursor move, other places are also affected.
- Sleep for IME, it doesn't make wrong even w/o the sleep, but if you confirm it is needed, I can include.
Why do you use it only for +i/+u/+o and not for i/u/o?

**Comment by rcmdnk** [comment]
About Visual Studio Code, I got it.

For OneNote, thank you for the link.
I'm still not sure if it is only for j/k or it affects on others (such ^u = {Up 10} or such +j = `Send,{Down}{Home}{BS}{Space}{Left}`).
But as a first implementation, such minimal things are enough, I think.

About IME, ok then it can be included.
I tested with this 200us sleep, but didn't feel a stress. So it is ok.

I will merge them and update some in tool tip things.

**Comment by BlueDrink9** [comment]
I have some thoughts on reverting the onenote and vscode changes. 

For vscode, there is now a very good native vim plugin that works much better than this script. 

As for onenote, I plan on shortly updating idvorkin/vim-keybindings-for-onenote to use this script as a submodule for non-specific things. That program has a fix for up and down. If I can do that, shall I submit a pr to remove onenote code from here and suggest people plug in the onenote script instead?

**Comment by rcmdnk** [comment]
If you want to remove these programs,
you can remove them from settings. (and it is kept after restarting.)

For onenote, I do not use onenoe usually and do not know details of the problem.
It is good if these fixes are included here,
but not sure how useful if separated scripts are needed only for onenote.

**Comment by rcmdnk** [comment]
@luciferz2012 

I removed these sleep at the recent commit: https://github.com/rcmdnk/vim_ahk/commit/6d25aab480f6d803ceaa77a58438b01a81e593a1#diff-eee302bfdd89fc0ace2b58429df53ad3
as I could not reproduce on current my Windows 10 (Japanese IME, for both Microsoft IME and Google IME).

If you have still the same problem,
please re-open this PR or make new issue.

**Pull request merged**
