### PR TITLE
Get tests working again, minor refactors and fixes

### PR DESCRIPTION
**Pull request by BlueDrink9**
Also some refactoring and minor bug fixes, and gets tests working again (at least on my machine).

Split and fixed from discussion in #60

### CODE REVIEW

**Comment by rcmdnk** [comment]
This is not possible to merge, as this includes caret updates.
In addition, this is just a remaining part of #60 and still has some reversion or update on update in commits...

**Comment by BlueDrink9** [comment]
Yes, this is branched off my Caret branch. I can probably rebase it if you want.


> reversion or update on update in commits...

Which ones? These are all very distinct changes in my opinion

**Comment by rcmdnk** [comment]
> Yes, this is branched off my Caret branch. I can probably rebase it if you want.
It is not possible to merge a branch which is not based on this master branch.
#60 still has a problem and must be changed.
Then, this branch will be not mergeable.

If there are too much different changes, it will take a lot of time to confirm all as you saw in #60.
This PR also includes many different changes and can not confirm everything.
Even if some of them seems fine, some of them may be not acceptable.
If you want, I will pick up and implement from some of your updates, but I can not push merge button for such a PR.

**Comment by BlueDrink9** [comment]
Sure. I'll rebase this one back to master.

**Comment by rcmdnk** [comment]
Please check the comment on `SetTooltipAtCaret`.
In addition, they are just for the stating point.

Then, we can start the discussion finally.

We need to discuss how we should implement such a new function.
At least I think the caret function should not be a default,
as it makes a lot of confusion that the caret remains thick at other than wordpad or onenote.
It makes wrong also on search column of Windows.
(Remaing thick and users can not revert even if they stop vim_ahk. Only the way is that they go to wordpad or onenote and switch to insert mode. )

**Comment by BlueDrink9** [comment]
> We need to discuss how we should implement such a new function.
At least I think the caret function should not be a default,
as it makes a big confusion that the caret remains thick at other than wordpad or onenote.
It makes wrong also on search column of Windows.
(Remaing thick and users can not revert even if they stop vim_ahk. Only the way is that they go to wordpad or onenote and switch to insert mode. )

This should have been a comment on the other PR

**Comment by BlueDrink9** [comment]
I don't see a comment on `SetTooltipAtCaret`

**Pull request merged**
