### PR TITLE
Remove executables and add buildscript + appveyor setup

### PR DESCRIPTION
**Pull request by BlueDrink9**
Add a setup script for [appveyor ci](https://ci.appveyor.com/) that automatically builds the scripts into an exe and uploads them as a draft release. Only builds on tags, and creates release named after that tag.

May require some tweaking for the upstream, and would need setting up appveyor access and replacing the auth token.

Merging this would ensure the exe is always up to date with releases.

### CODE REVIEW

**Comment by BlueDrink9** [comment]
Oh, sorry, I see you are attempting to integrate it in cfc1e2654e5a1161238c324a39a253eca91ca1ab

I forgot to change one thing: When I was testing it with onenote, the test script was too complicated to get working on appveyor. The reason is because they don't draw the UI in the remote desktop unless someone logs in, so all the ifWinActive calls hang, causing eventual failure. With notepad, it's fast enough that it may work without the ifWinActive calls, but that'll require more testing.

In the meanwhile, if you change [`build.bat /t](https://github.com/rcmdnk/vim_ahk/blob/cfc1e2654e5a1161238c324a39a253eca91ca1ab/appveyor.yml#L49) to `build.bat` it should disable the tests and let it build.

You'll also need to create different encrypted access keys within appveyor for your git, of course. They're at the top of that file.

**Comment by BlueDrink9** [comment]
Oh, also, the final line of `appveyor.yml` assumes the existance of vim_ime.ahk, which doesn't actually exist! If you add the code you used to create vim_ime.exe, it will work. Otherwise, remove that line.

**Comment by BlueDrink9** [comment]
I understand. Happy to help out. I'll update the pull to hopefully make it easier!

**Comment by BlueDrink9** [comment]
@rcmdnk if you follow the changes in the previous comment (when you have time) on branch `ci-pull-check`, then tag the commit, it should automatically create a release for that tag and add compiled `exe`s for that version.

If you still have the code for `ime.exe`, that might be worth including in the repo and building with this method. You could possibly include it as a subrepo? Or use curl to get the text from a gist, then compile that only on the appveyor server. Would be more transparent than including a misc exe without its source...

**Comment by rcmdnk** [comment]
Thank you for your suggestions.

I'm sorry that I could not have enough time to confirm all

For exe files, I think it is better to put in the other place (maybe just in branch)
otherwise, any local repository is affected by this auto push.

Not only ime, maybe better to put non-vim.ahk files in directories.

Anyway, I've not forgotten this and taken some time for it...

**Comment by BlueDrink9** [comment]
With regards to this running on auto-push, that setting can be changed so it only runs on tags, or only runs on certain branches. If you let me know exactly when you would like the exes to build, I'll configure the script. 

Currently it's configured to add the exes to a release tag on github. But it does need an access token first.

**Comment by BlueDrink9** [comment]
@rcmdnk have you had any more time/motivation to look at merging this?

**Comment by rcmdnk** [comment]
sorry, I could not take time for it, but still, have motivation...
On the other hand, recently I wonder if we can use GitHub Actions to do such a build.

**Comment by BlueDrink9** [comment]
Maybe. I'll look into it for you

**Comment by rcmdnk** [comment]
Commits were merged and 
the first release was created as 
[v0.5.0](https://github.com/rcmdnk/vim_ahk/releases/tag/v0.5.0) by Appveyor.
 
I also tried to run the test (appveyor_setup.ahk), but it was stuck:
https://ci.appveyor.com/project/rcmdnk/vim-ahk/builds/27618783

Anyway, thank you for this.
Now the exe file is separated from the code and listed on the release page, cool 😎 !

**Comment by BlueDrink9** [comment]
Wicked, glad to hear.
Yeah, the automated tests on CI were always pretty tricky. IIRC I never got them working, because things like `winwaitactive` require the gui, which appveyor disables until you remote in. Tried a bunch of tricks to get around it. That was on onenote though, where `winwaitactive` was actually required - I imagine you could get around it for this version by removing them and relying on `sleep` to just swap between vim and notepad windows.

Overall though I think the tests may just be more useful to run manually.

**Pull request closed without merging**
