### PR TITLE
Fix some failing tests

### PR DESCRIPTION
**Pull request by BlueDrink9**
Removes a couple of sleeps that seem unnecessary, but prevented the testscript from working properly.

### CODE REVIEW

**Comment by BlueDrink9** [comment]
If we change the testscript keydelay to 200, it should work. 
I was suprised that they were necessary, I never had an issue with them on my machine. If they're necessary though, ignore this

**Comment by BlueDrink9** [comment]
Ah, I see. It's for ime?
Maybe we can add a check, and only sleep if ime is used in settings?
My fork disables user settings when testing, so I could include that.

**Comment by rcmdnk** [comment]
Even if it is set only if ime is used,
the test fails if ime is enabled.
That is not a desirable state.

If this sleep breaks any normal usage, then it should be considered again.
Otherwise, if it fails only when the test (switching to fast by scripting),
I would like to keep them.

**Comment by BlueDrink9** [comment]
I have added a quick check that only sleeps if you are using IME. It won't fix the tests if IME is still enabled, but I think it's good in general for users that don't use IME to not have that delay (which is otherwise unnecessary for them)

**Comment by rcmdnk** [comment]
`VimRestoreIME` is just an option to restore IME status when you switch back to Insert mode.
It can be disabled even if OS IME is enabled, so that it can not be used.
On the other hand, VIM_IME_GET returns if IME is enabled or not:
https://github.com/rcmdnk/vim_ahk/blob/master/vim.ahk#L647
It could be used here.

Although it is not so good to make a code to pass the test only for the special case,
it is ok for the initial installation of these tests.

**Comment by BlueDrink9** [comment]
Thanks for that. Really, my point with this last check isn't to pass the tests - although that is a side benefit. The point is that the delay is unnecessary if you don't use it, which I'm sure is a big chunk of the userbase here. We should be minimising unnecessary delays, right?

**Comment by rcmdnk** [comment]
You are right.

By the way, now I tested on my PC if the previous problem can be reproduced or not.
It seems it doesn't happen for both Microsft IME and Google IME.

Therefore, I would like to include your first change (just deleting sleep).

I close this PR but the change was included in https://github.com/rcmdnk/vim_ahk/commit/6d25aab480f6d803ceaa77a58438b01a81e593a1#diff-eee302bfdd89fc0ace2b58429df53ad3

sorry for not taking your PR directly, but thank you for the iterations.

**Comment by BlueDrink9** [comment]
Fine by me. Thanks for your continued maintenance!

**Pull request closed without merging**
