### PR TITLE
jj instead of Esc

### PR DESCRIPTION
**Pull request by satsaeid**
+ supporting jj and تت instead of Esc
if you hit jj fast (Not hold) then it will count as Esc
+ it support for two language (Persian and English)
when you are in Persian and hit تت it will change the keyboard
layout to English automatically and then goes in Normal mode

### CODE REVIEW

**Comment by rcmdnk** [comment]
Thank you for the pull request.
Here are my comment:

About `jj`, I've tested and it works, but double push timing is very severe (or sometime doesn't work even I push in a short time).
And sometime it works unexpectedly.

I'm not sure how `Input` affects on others, so I need test more.

>when you are in Persian and hit تت it will change the keyboard
>layout to English automatically and then goes in Normal mode

I could not understand this from the codes (maybe around `PostMessage`).
Could you explain a bit more detail?

Maybe these codes can be included as option.
Currently it doesn't have any GUI menus so first it should be hard coded option like `VimVerbose`,
but I plan to make some menu options to change these options.

Not sure about following change.
```
-j::VimMoveLoop("j")
+SC024::VimMoveLoop("j")
```

About icon settings, they are necessary when this script is included by other script.
These change cannot be merged.

**Comment by satsaeid** [comment]
Thank you for review.
the purpose from `SC024 `instead of `j` is : multi-language supporting because when you switch to another language, then `j` converted to other key, `SC024 `is the corresponding value of `j` key, so if you switch to another layout like Persian, Chinese or anything else, then all of them will work just fine.
**about your comment :** 

> "About jj, I've tested and it works, but double push timing is very severe (or sometime doesn't work even I push in a short time).
> And sometime it works unexpectedly."

you are true ! I need to optimize its delay to be better than, thank you :)
 **about your comment :**

> I could not understand this from the codes (maybe around PostMessage).
> Could you explain a bit more detail?
sure ! 
```
if(CheckKeyboardLayout() = 0x4290429) ; 0x4290429 is Farsi(Persian) https://www.autohotkey.com/docs/misc/Languages.htm
			{			 
				PostMessage, 0x50, 2, 0,, A ; 0x50 is WM_INPUTLANGCHANGEREQUEST
				VimSetMode("Vim_Normal")				
			}
```
the return value of `CheckKeyboardLayout()` function is a number like `0x4290429` corresponding the current language on your system right now (ex: is it Persian or English right now), so it checks if it's Persian then change it to English (`PostMessage` function change the language from Persian to English)
btw I have a new Idea about this section of code, we can change the `if` so if it wasn't English then change it to English, with this change it can support all languages not just Persian.

**about your comment :** 

> About icon settings, they are necessary when this script is included by other script.

My aim wasn't changing the Icons and Icon settings, it was a private changes for myself, my meaning is I didn't want to pull request them actually, just the jj commit was my aim

**about your comment :** 

> Maybe these codes can be included as option.
it will be amazing, yes it's really good Idea ! Nice

**Comment by rcmdnk** [comment]
>the purpose from SC024instead of j is : multi-language supporting because when you switch to >another language, then j converted to other key, SC024is the corresponding value of j key, so if >you switch to another layout like Persian, Chinese or anything else, then all of them will work just fine.

This setting is for "Normal Mode", so it doesn't need because you change a layout by `PostMessage`, does it?
Otherwise you need to change all others (`h`, `k`, `l`, etc...), I think.

It is necessary rather at `Input, jState, I T0.09 V L2, {j}{?},j,? ;{vk4Asc024 up} `, isn't it?

>btw I have a new Idea about this section of code, we can change the if so if it wasn't English then >change it to English, with this change it can support all languages not just Persian.

so you have a way to change it back to Persian separately?
(Just out of curiosity, how do you do on Vim? Vim understands Persian layout or you need to change layout?)

**Comment by satsaeid** [comment]
> This setting is for "Normal Mode", so it doesn't need because you change a layout by PostMessage, does it?
> Otherwise you need to change all others (h, k, l, etc...), I think.

just for j is needed but not for h, k, l, etc because when for example your layout (right now) is on Persian, your j key is ت not j, and you are in Insert mode right now, and you want to go in normal mode via pressing jj so you are typing تت and it's not jj. so the only key that needs to change is j not others.

> It is necessary rather at Input, jState, I T0.09 V L2, {j}{?},j,? ;{vk4Asc024 up}, isn't it?

yes you are right.

> so you have a way to change it back to Persian separately?

yes, it's a windows feature, by pressing Alt+Shift you can always change the current layout to another one. in everywhere (in Vim too).

**Comment by rcmdnk** [comment]
> when for example your layout (right now) is on Persian, your j key is ت not j, and you are in Insert mode right now, and you want to go in normal mode via pressing jj so you are typing تت and it's not jj. so the only key that needs to change is j not others.

```
 #If WInActive("ahk_group VimGroup") and (InStr(VimMode,"Vim_")) 
 j::VimMoveLoop("j") 
```

This is enabled only in normal mode (i.e. English layout), not in insert mode.

**Comment by satsaeid** [comment]
> This is enabled only in normal mode (i.e. English layout), not in insert mode.

yes and no ;)
please notice this section of code : 
```
**~*SC024 up::**
Input, jState, I T0.09 V L2, {j}{?},j,? ;{vk4Asc024 up}
		if(ErrorLevel = "EndKey:J"||ErrorLevel = "EndKey:?")
		{          
			sleep,20			
            SendInput,{BackSpace 2}            
			sleep,200
			VimSetMode("Vim_Normal")
			;Send,{Esc}
			sleep,100
			if(CheckKeyboardLayout() = 0x4290429) ; 0x4290429 is Farsi(Persian) https://www.autohotkey.com/docs/misc/Languages.htm
			{			 
				PostMessage, 0x50, 2, 0,, A ; 0x50 is WM_INPUTLANGCHANGEREQUEST
				VimSetMode("Vim_Normal")				
			}				
		}
Return
#If WInActive("ahk_group VimGroup") and (InStr(VimMode,"Vim_"))
; 1 character
h::VimMoveLoop("h")
**SC024::VimMoveLoop("j")**
```

I bolded some sections in that code, the first Bold section active when we are in Insert mode, and the second one will active when we are in Normal mode (you are true), **but** : these two sections most be exactly like each other, otherwise they will confuse ! so that's why I changed the second one to **SC024** too.

**Comment by rcmdnk** [comment]
so, it is just for avoiding confusion, right?
Then it is rather clear if you put some comment before `~*SC024 up::` about `j`.

`SC024::VimMoveLoop("j")` only in hjkl makes another confusion, I think.

**Comment by satsaeid** [comment]
yes you are right, it would be better to put some comment there, and yes the only confusion is about j key

**Comment by rcmdnk** [comment]
ok, then if you make pull request only for `jj`, with option setting,
I can merge it.
Or I will add these codes by myself if you want.

**Comment by satsaeid** [comment]
First of all thank you very much for your effort and your notice to my codes :)
sure ! it's ok you can add those codes yourself to it.
thank you again.

**Comment by rcmdnk** [comment]
After some tests, I noticed that if we use `SC024` in any place,
`j` related mappings are broken.

It is not only `j::VimMoveLoop("j")`, but also `^j`, `+j` are affected.
I'm not sure it is AutoHotkey's expected behavior or something wrong in this script.

Although it works if `SC024` is used for these mappings, 
it is too risky to include it with such a effect.

I can include it as simply `jj` (i.e. `~j up:: ...`), it is interesting feature.

About `Input`, why do you need `?`.
We can drop 
`MatchList` (the last argument) because they are exactly same as `EndKeys`, right?

**Comment by satsaeid** [comment]
you are right, I wrote these feature for another programs too (like VSVim an extension in visual studio code) but here no need to ? and SC024

**Comment by satsaeid** [comment]
so finally I think you can wrote those codes like this : 
```
; here we can check if we are in insert mode
; and if we pressed (j or ت) then we have to go
; in Vim_Normal mode !!
#If WInActive("ahk_group VimGroup") and (InStr(VimMode,"Insert"))
;j key : {vk4Asc024}
~*j up::
Input, jState, I T0.09 V L2, {j},{j} ;{vk4Asc024 up}
		if(ErrorLevel = "EndKey:J")
		{          
			sleep,20			
            SendInput,{BackSpace 2}            
			sleep,200
			VimSetMode("Vim_Normal")
			;Send,{Esc}
			sleep,100
            LangID:= CheckKeyboardLayout()
			if(LangId!="0x4090409")and(LangId!="0x0091009") ; 0x0091009 = English_Canadian, 0x4090409 is English_United_States, 0x4290429 is Farsi(Persian) https://www.autohotkey.com/docs/misc/Languages.htm
			{             
				PostMessage, 0x50, 2, 0,, A ; 0x50 is WM_INPUTLANGCHANGEREQUEST
				VimSetMode("Vim_Normal")				
			}				
		}
Return
#If WInActive("ahk_group VimGroup") and (InStr(VimMode,"Vim_"))
```

**Comment by rcmdnk** [comment]
~*j up::

I think this key should be:

    ~j up::

No need to allow modifiers.
I have bind of `!^j` to bottom arrow, and push more than twice in a short time.

    Input, jState, I T0.09 V L2, {j},{j} ;{vk4Asc024 up}
 
This should be

    Input, jState, I T0.09 V L1, {j}

It expects only 1 character, so it should be `L1`.

As `j` is EndKeys, the last `{j}` (Match) doesn't work.
(If it works, we should prepare `(ErrorLevel = "Match")`, too.)

Maybe `T0.1` is enough instead of `T0.09`? (just to simplify)

If it is `~j`, you need to change keyboard layout before using `j`, don't you?
If so, `LangID` part is meaningless.

In addition, there are some layouts which have same placement of alphabets as US, but only others are different.
For these keyboards, layout should not be changed.
So it should be white list instead of black list.

**Comment by satsaeid** [comment]
Sure ! and nice 👍 

> In addition, there are some layouts which have same placement of alphabets as US, but only others are different.

I didn't think about it, I don't know what will happen for those layouts

**Comment by rcmdnk** [comment]
Now `jj` is included in the master branch.
It is disabled by default. You can enable it from right click menu of task tray icon (VimMenu->VimJJ).
This menu is currently not saved (will try to implement configuration file later).

**Comment by satsaeid** [comment]
Thank you :)

**Comment by rcmdnk** [comment]
Now `jj` can be enabled from menu settings (tray icon right click, or Shift-Ctrl-Alt-v).
The settings are stored and read at the next start.

**Pull request closed without merging**
