### PR TITLE
Add keybinds refer to ranger which is a console file manager with VI for the Q-Dir.

### PR DESCRIPTION
**Pull request by scutxd**
Q-Dir the Quad Explorer for Microsoft's Windows Desktop and Server.
I think it is very useful in high resoution screen as it can provides 4 windows. But it lacks the vi sytle keybinds.
So i have add some keybinds in vi sytle to improve.

### CODE REVIEW

**Comment by rcmdnk** [comment]
Thank you for PR!
It seems fine to implement for Q-dir with new Group.
Give me a little time to check it with Q-dir. (try to make a time in this weekend, or next week...)

**Comment by rcmdnk** [comment]
Q-Dir settins were included in v0.8.6, thanks!

**Comment by BlueDrink9** [comment]
@rcmdnk why did this change introduce a `.vscode` folder? That is editor-specific and nothing to do with this project. I think it should have been removed. `.vscode/` is a common line in most gitignores

**Comment by rcmdnk** [comment]
Although it is editor specific,
I thought it is harmless and it might help others who try to develop with Visual Studio Code.
Honestly I'm not familiar with vscode and not sure if it is changed at developping.
If it is not stable, or not useful by fixing AHK path, I agree to remove it.

**Comment by BlueDrink9** [comment]
Aren't you concerned about clutter? There are many different editors, and it would be daft to include editor-specific configuration files for any that people might use. More files in a repo can be confusing, so they should serve an important purpose. 

 It doesn't do very much at all, and is better served by vscode AHK plugins. Also, and probably most importantly, having in the git repo overrides the vscode settings of anyone else using it, for example if someone's AHK path is different to default and already specified in their own vscode config.

IMO, this file absolutely does not belong in a project git repo and should be removed.

**Comment by rcmdnk** [comment]
ok, let's remove it.

**Pull request merged**
